### ISSUE TITLE
Upgrading the async-http-client dependency

### ISSUE THREAD

**Issue by dkharrat** [opentok/Opentok-Java-SDK#75] opened 2015-07-12 20:48 UTC
The async-http-client dependency the SDK is currently using is over 4 years old. In my project, I'm using another library that depends on a newer version of async-http-client, and therefore Opentok is crashing since my build is picking up the newer version of async-http-client defined by the other dependency, which does not happen to be compatible with the version OpenTok is using.

Can the OpenTok SDK use the latest version (1.9.x) of async-http-client?

**Comment by aoberoi** [comment] 2015-07-31 19:26
@dkharrat interesting point. the current version specifier is: `[1.6.1,1.9)`. what do you think about replacing it with `[1.6.1,2.0[`? this translates to "all versions above 1.6.1 and less than 2.0".

**Comment by aoberoi** [comment] 2015-07-31 19:34
just got a change to see #76 and here are some thoughts:

if the >= 1.9.0 API is somehow different from < 1.9.0, then they clearly are not following semantic versioning in the async-http-client project.

in terms of which version is right for this project, 1.8.15 is less than 1 year old, so i don't think its unreasonable to stick to that for now and a little while longer. based on the age of dependencies in most Java based projects, and how popular the library is, it seems like upgrading past 1.9.0 might actually cause issues for more people.

i don't know what the right answer is here yet, but another option is to maintain another prerelease branch that gets the newer versions, and developers like yourself can follow that.

**Comment by aoberoi** [comment] 2015-07-31 19:40
reference for version specifiers: http://ant.apache.org/ivy/history/trunk/settings/version-matchers.html

apparently gradle just borrows from ivy

**Comment by dkharrat** [comment] 2015-08-07 03:57
Yeah, with those API changes in async-http-client, it didn't follow semantic versioning. I believe the changes were introduced in the 1.8.x release. Good idea about using `2.0[` The current version of async-http-client is 1.9.30. The 1.9.x release has been out for over 6 months now and has been stable. I think it should be fine to set the minimum version specifier to 1.8, since it's still compatible. A user of the SDK can always force a specific version between that range if they need to for any reason.

I'll push another change to change the minimum version specifier to 1.8.x.

**Comment by dkharrat** [comment] 2015-08-25 19:43
@aoberoi I just tested with version async-http-client 1.8.16 and it didn't compile due to a slight API change. I recommend sticking with 1.9.x, which is the currently maintained version of the library and has been released for a while.

Also, I just pushed a change to update the version specifier to `[1.9,2.0[` as you suggested.

**Comment by aoberoi** [comment] 2015-08-26 22:57
@dkharrat okay, i've decided on a plan of action.

first, i'll make another PR which limits the async-http-client dependencies to version 1.8.x (fixing #79), merge that in, and make a release (v2.3.2).

next, i'll merge your PR, which bumps the async-http-client dependency to 1.9.x (fixing #75), and make a release with an incremented minor version number (v2.4.0).

does this sound good (cc @mikebell90)

**Comment by aoberoi** [comment] 2015-08-26 23:00
one item to note, 2.4.0 will essentially drop support for Java 6, because the 1.9.x line of async-http-client also drops support for it. for this reason i was considering making the version number 3.0.0, but it seems like that would imply a breaking change in our own API, which is not true.

**Comment by dkharrat** [comment] 2015-08-27 23:22
@aoberoi I like your plan, it sounds reasonable.

With regards to using version 2.4.0 vs 3.0.0, does OpenTok 2.3.x officially support Java 6? If so, to follow the spirit of semantic versioning, it might make more sense to bump the version to 3.0.0 for dropping Java 6 support (also issue mojombo/semver#148 implies this).

I wholeheartedly agree on dropping support for Java 6 regardless, so I think that's a good change.

**Comment by aoberoi** [comment] 2015-09-03 20:22
@dkharrat i'm looking at the following quote, which leads me to think it should be either a minor or a patch version change when we drop java 6 (from semver.org):

> What should I do if I update my own dependencies without changing the public API?
> 
> That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. I would usually expect additional code for the latter instance, in which case it's obviously a minor level increment.

i'd rather interpret whats in the official spec than the discussion on github. so i'm going ahead with the plan as above.

**Comment by aoberoi** [comment] 2015-09-03 20:38
first part of plan is #80

**Comment by MattWeiler** [comment] 2016-01-25 19:44
I just added the **opentok-server-sdk** dependency to my maven project and something strange is happening.


# The Problem #
When I try to run the **createSession(SessionProperties properties)** method on the **com.opentok.OpenTok** class, I get an exception stating that the the **setParameters** method within the **com.ning.http.client.AsyncHttpClient.BoundRequestBuilder** class of the **async-http-client** library is missing.

When I analyzed which version of the **async-http-client** library is being used it was version **1.9.0-BETA-24**.
I guess that method was removed from a more recent version and is thus breaking the **opentok-server-sdk**.


# Hacky Fix (*for those in need*) #
To make my project work, I just added a dependency for the **1.6.1** version of the same library before the **opentok-server-sdk** dependency in my **pom.xml** file.


# Possible Solution #
I think you guys either need to remove the upper-bounds of **1.9** from your **pom.xml** file or make your code work with the later version.
Anyone just trying to use your library will meet immediate failure and may not think that the issue is your **pom.xml** file.

Granted this is not your fault, this is clearly the naming of the **async-http-client** library, but regardless it's causing an issue.

**Comment by aoberoi** [comment] 2016-02-04 22:56
just merged the fix for using 1.9.x version of the library in #86

**Closed by aoberoi** 2016-02-04 22:56 UTC

**Comment by stegmann-idnow** [comment] 2016-02-05 08:18
@aoberoi  When you are planning a release?
