### ISSUE TITLE
NoSuchMethodFound Exceptions and com.ning dependency

### ISSUE THREAD

**Issue by rhainer** [opentok/Opentok-Java-SDK#118] opened 2016-09-22 21:22 UTC
the pom file of your Server SDK should use a specific version of the com.ning dependency because the selected one leads to NoSuchMethodFound Exceptions.

 

<dependency> 
<groupId>com.tokbox</groupId> 
<artifactId>opentok-server-sdk</artifactId> 
<version>2.3.2</version> 
</dependency>

Results in:

[INFO] +- com.tokbox:opentok-server-sdk:jar:2.3.2:compile 
[INFO] | +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.2:compile (version selected from constraint [2.3.1,2.99999)) 
[INFO] | | +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0:compile 
[INFO] | | - com.fasterxml.jackson.core:jackson-core:jar:2.8.2:compile 
[INFO] | - com.ning:async-http-client:jar:1.9.0-BETA24:compile (version selected from constraint [1.6.1,1.9)) 
[INFO] | - io.netty:netty:jar:3.9.5.Final:compile

---

My suggestion:

 

<dependency> 
<groupId>com.ning</groupId> 
<artifactId>async-http-client</artifactId> 
<version>1.6.1</version> 
</dependency>

 

<dependency> 
<groupId>com.tokbox</groupId> 
<artifactId>opentok-server-sdk</artifactId> 
<version>2.3.2</version> 
</dependency>

**Comment by aiham** [comment] 2017-07-04 01:36
Duplicate of #97

**Closed by aiham** 2017-07-04 01:36 UTC
